config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :tasks
  end
  resources :categories
  resources :tasks
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    validates :name, presence: true
    validates :description, presence: true

    scope :sorted, -> { order(:name) }

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category

    enum priority: [:low, :medium, :high]

    validates :title, presence: true
    validate :due_date_after_created_at
    validates :priority, presence: true

    def due_date_after_created_at
        if due_date.present? && created_at.present?
            if days_until_due < 0
                errors.add(:due_date, "must be at least one day later than the one created date.")
            end
        elsif due_date.present?
            if days_until_due_date < 0
                errors.add(:due_date, "must be at least one day later than a current date.")
            end
        end
    end
    
    # Adicione esta função para calcular a diferença em dias entre created_at e due_date
    def days_until_due
        if due_date.present?
            (Date.parse(due_date.strftime('%Y-%m-%d')) - Date.parse(created_at.strftime('%Y-%m-%d'))).to_i
        else
            0  # ou outra lógica, dependendo do seu caso
        end
    end
    
    # Função para calcular quantos dias faltam até o due_date
    def days_until_due_date
        if due_date.present?
            (Date.parse(due_date.strftime('%Y-%m-%d')) - Date.parse(Date.today.strftime('%Y-%m-%d'))).to_i
        else
            0  # ou outra lógica, dependendo do seu caso
        end
    end

    def percentage_days_remaining
        total_days = days_until_due
        remaining_days = days_until_due_date
        if total_days > 0
            completion_percentage = (remaining_days.to_f / total_days.to_f) * 100
            return completion_percentage.round(2) # rounding to two decimal places
        else
            0  # handle the case where total_days is 0 to avoid division by zero
        end
    end

    private

end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :validatable,
          :confirmable,
          :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
      
    private
      
    def user_not_authorized
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.sorted
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :categories_url, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
        format.json { render :categories_url, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ edit update destroy ]
  before_action :set_category, except: %i[edit update ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @category.tasks.sort_by { |task| task.percentage_days_remaining }
  end

  # GET /tasks/new
  def new
    @task = @category.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @category.tasks.new(task_params)
    if @task.save
      redirect_to category_tasks_path(@task.category)
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to category_tasks_path(@task.category)
    else
      render :edit
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to category_tasks_path(@category)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
      @currentCategory = Category.find(@task.category_id)
      authorize @currentCategory
    end

    def set_category
      @category = Category.find(params[:category_id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :completion, :priority, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

    def count_completed_tasks_in_category(category)
        return category.tasks.where(completion: true).count
    end
    
    def count_incomplete_tasks_in_category(category)
        return category.tasks.where(completion: false).count
    end

end

app/helpers/tasks_helper.rb
module TasksHelper

    def count_tasks_by_priority_and_status(priority, completion, category_id)
      return Task.where(priority: priority, completion: completion, category_id: category_id).count
    end

    def month_day_comma_year(datetime)
      datetime.strftime('%d/%m/%Y')
    end

    def progressbar_type(task)
      if task.completion
        return 'bg-secondary'
      end
      percentage = task.percentage_days_remaining.round(2)
      if  percentage <= 33.33
        return 'bg-danger'
      end
      if  33.33 < percentage && percentage <= 66.66
        return 'bg-warning'
      end
      if  66.66 < percentage
        return 'bg-success'
      end
      return ''
    end

    def completion_due_date_type(task)
      if task.completion
        return 'bg-secondary'
      else
        return 'bg-danger'
      end
    end

    def count_completed_tasks(tasks)
      tasks.count { |task| task.completion }
    end

    def count_incomplete_tasks(tasks)
      tasks.count { |task| !task.completion }
    end


end

app/views/categories/_category.html.erb
<div class="accordion-item">
  <h2 class="accordion-header">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= dom_id category %>" aria-expanded="false" aria-controls="flush-collapse<%= dom_id category %>", style="background-color: white;">
      <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= category.name %></h5>
        </div>
        <hr>
        <h4>
          <span class="badge bg-danger rounded-pill">
            Incompleted tasks: <%= count_incomplete_tasks_in_category(category) %>
          </span>
          <span class="badge bg-secondary rounded-pill">
            Completed tasks: <%= count_completed_tasks_in_category(category) %>
          </span>
        </h4>
      </a>
    </button>
  </h2>
  <div id="flush-collapse<%= dom_id category %>" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
    <div class="accordion-body">
      <div class="card">
        <div class="card-body">
          <%= category.description %>
        </div>
      </div>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example", style="padding-bottom: 18px">
      <%= button_to "Open tasks", category_tasks_path(category), method: :get, class: 'btn btn-outline-success' %>&nbsp;&nbsp;
      <%= button_to "Edit this category", edit_category_path(category), method: :get, class: 'btn btn-outline-primary' %>&nbsp;&nbsp;
      <%= button_to "Destroy this category", category, method: :delete, class: 'btn btn-outline-danger' %>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, input_html: {rows: 13} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to "Back to Categories", categories_path, class: 'btn btn-outline-primary' %>
  </div>

<% end %>

app/views/categories/_topnavbar.html.erb
<nav class="navbar bg-body-tertiary">

  <%= button_to new_category_path, method: :get, class: 'btn btn-outline-primary', style: 'margin-left:20px;' do %>
    <%= image_tag("https://icons.iconarchive.com/icons/graphicloads/100-flat-2/48/pen-icon.png", alt: "Back") %>
    New category
  <% end %>

  <div class="dropdown" style='margin-right:20px;'>
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://icons.iconarchive.com/icons/graphicloads/100-flat-2/48/contacts-icon.png" alt="Back Arrow" class="mr-2">
      <%= current_user.email %>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item' %></li>
      <li><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
    </ul>
  </div>

</nav>

app/views/categories/edit.html.erb
<center>
  <%= render "form", category: @category %>
</center>

app/views/categories/index.html.erb
<%= render 'topnavbar' %>

<center class="content-with-navbar">
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div id="categories">
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    </div>
  </div>
</center>

<br>

app/views/categories/new.html.erb
<center>
  <%= render "form", category: @category %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>

        html {
            padding: 0;
            margin: 0;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding-bottom:  1%;
        }

        .content-with-navbar{
            min-height: calc(100% - 90px);
        }

        .priority {color: #3498db}
        .priority.low {color: #3498db}
        .priority.medium {color: #f39c12}
        .priority.high {color: #e74c3c}
        .completion {color: #3498db}
        .completion.true {color: #3498db}
        .completion.false {color: #e74c3c}

        .vertical-bar::before {
            content: '|';
            margin: 0 10px; /* Ajuste a margem conforme necessário */
            color: #000; /* Cor da barra vertical */
          }

        center {
            justify-content: center;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            border-radius: 8px;
            width: 80%;
            align-items: center;
            margin-top:25px;
            margin-left: auto;
            margin-right: auto;
        }

        h1 {
            color: #333;
        }

        p {
            margin: 10px 0;
            color: #666;
        }

        .priority {
            color: #e44d26;
        }

        .completion {
            color: #34a853;
        }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_accordion_item.html.erb
<div class="accordion-item", style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);border: 1px solid rgba(0, 0, 0, 0.1);"
  <h2 class="accordion-header">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= dom_id task %>" aria-expanded="false" aria-controls="flush-collapse<%= dom_id task %>", style="background-color: white;">
      <%= render 'accordion_item_header', task: task %>    
    </button>
  </h2>
  <div id="flush-collapse<%= dom_id task %>" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
    <div class="accordion-body">
      <%= render 'accordion_item_body', task: task %>    
    </div>
  </div>
</div>

app/views/tasks/_accordion_item_body.html.erb
<div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1">
        <%= task.description %>
    </h5>
</div>
<div class="btn-group" role="group" aria-label="Basic example" , style="padding-bottom: 18px">
    <%= button_to "Edit this task" , edit_category_task_path(@category, task), method: :get,class: 'btn btn-outline-primary' %>&nbsp;&nbsp;
    <%= button_to "Destroy this task" , category_task_path(@category, task), method: :delete, class: 'btn btn-outline-danger' %>
</div>

app/views/tasks/_accordion_item_header.html.erb
<a href="#" class="list-group-item list-group-item-action active" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            <%= task.title %>
        </h5>
        <h4>
            <span class="badge <%= completion_due_date_type(task) %> rounded-pill">
                Due date <%= month_day_comma_year(task.due_date) %>.
            </span>
        </h4>
    </div>
    <p class="mb-1">
        <div class="progress" role="progressbar" aria-label="Example with label" aria-valuenow="<%= task.percentage_days_remaining.round(2) %>" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar <%= progressbar_type(task) %>" style="width: <%= task.percentage_days_remaining.round(2) %>%"></div>
        </div>
    </p>
    <h4>
        <span class="badge bg-secondary rounded-pill">
            Created at <%= month_day_comma_year(task.created_at) %>
        </span>
        <span class="badge bg-secondary rounded-pill">
            Number of days available <%= task.days_until_due_date %>.
        </span>
    </h4>
</a>

app/views/tasks/_form.html.erb
<%= simple_form_for [@category, @task] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :title %>
    <%= f.input :description, input_html: {rows: 18} %>
    <%= f.input :due_date %>

    <div style="display:flex;">
      <div class="card", style="flex:1;">
        <div class="card-body">
          <%= f.label :priority, class: 'control-label' %>
          <div class="form-group", style="padding-top:10px;">
            <div class="btn-group" role="group" aria-label="Vertical radio toggle button group">
              <% Task.priorities.keys.each do |priority| %>
                <input type="radio" class="btn-check" name="task[priority]" id="<%= "priority-#{priority}" %>" <%= f.radio_button :priority, priority, class: 'd-none' %>
                <label class="btn btn-outline-primary" for="<%= "priority-#{priority}" %>"><%= priority.humanize %></label>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="card", style="flex:1;margin-left:10px;margin-right:10px;">
        <div class="card-body", style="display:flex;align-items: center;justify-content: center;">
          <div class="d-flex justify-content-center align-items-center">
            <div class="form-check form-switch">
              <%= f.check_box :completion, class: "form-check-input", role: "switch", id: "flexSwitchCheckCompletion" %>
              <%= f.label :completion, "Completion", class: "form-check-label", for: "flexSwitchCheckCompletion" %>
            </div>
          </div>
        </div>
      </div>
      <div class="card", style="flex:1;display:flex;align-items:center;justify-content:center;">
        <%= f.association :category, collection: Category.sorted, prompt: "Select Category" %>
      </div>
    </div>
  </div>

  <hr>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to "Back to tasks", category_tasks_path(@task.category), class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/tasks/_tab.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- Tabs verticais -->
    <div class="col-md-1">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-tab1" data-toggle="pill" href="#tab1" role="tab" aria-controls="tab1" aria-selected="true">High Priority</a>
        <a class="nav-link" id="v-pills-tab2" data-toggle="pill" href="#tab2" role="tab" aria-controls="tab2" aria-selected="false">Medium Priority</a>
        <a class="nav-link" id="v-pills-tab3" data-toggle="pill" href="#tab3" role="tab" aria-controls="tab3" aria-selected="false">Low Priority</a>
      </div>
    </div>
    <!-- Conteúdo das tabs -->
    <div class="col-md-10">
      <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="v-pills-tab1">
          <h2>Conteúdo da Tab 1</h2>
          <p>Texto da Tab 1...</p>
        </div>
        <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="v-pills-tab2">
          <h2>Conteúdo da Tab 2</h2>
          <p>Texto da Tab 2...</p>
        </div>
        <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="v-pills-tab3">
          <h2>Conteúdo da Tab 3</h2>
          <p>Texto da Tab 3...</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<%= render 'accordion_item', task: task %>

app/views/tasks/_topnavbar.html.erb
<nav class="navbar bg-body-tertiary">

  <%= link_to(categories_path, class: 'btn btn-outline-primary', style: 'margin-left:20px;') do %>
    <%= image_tag("https://icons.iconarchive.com/icons/graphicloads/100-flat-2/48/arrow-back-icon.png", alt: "Back") %>
    Back to Categories
  <% end %>

  <%= button_to new_category_task_path(@category), method: :get, class: 'btn btn-outline-primary' do %>
    <%= image_tag("https://icons.iconarchive.com/icons/graphicloads/100-flat-2/48/pen-icon.png", alt: "Back") %>
    New task
  <% end %>
    
  <div class="dropdown" style='margin-right:20px;'>
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://icons.iconarchive.com/icons/graphicloads/100-flat-2/48/contacts-icon.png" alt="Back Arrow" class="mr-2">
      <%= current_user.email %>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item' %></li>
      <li><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
    </ul>
  </div>

</nav>

app/views/tasks/edit.html.erb
<center>
    <%= render "form", task: @task %>
</center>

app/views/tasks/index.html.erb
<%= render 'topnavbar' %>

<center class="content-with-navbar">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">
        Incompleted Tasks
        <small>
          <h10>
            <span class="badge bg-danger rounded-pill">
              <%= count_incomplete_tasks(@tasks) %>
            </span>
          </h10>
        </small>
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">
        Completed Tasks
        <small>
          <h10>
            <span class="badge bg-secondary rounded-pill">
              <%= count_completed_tasks(@tasks) %>
            </span>
          </h10>
        </small>
      </button>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent" style="height:100%;">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <hr>
      <div class="container-fluid">
        <div class="row">
          <!-- Tabs verticais -->
          <div class="col-md-2">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
              <a class="nav-link active" id="v-pills-tab1" data-toggle="pill" href="#tab1" role="tab" aria-controls="tab1" aria-selected="true">
                High Priority
                <span class="badge bg-danger rounded-pill">
                  <%= count_tasks_by_priority_and_status('high', false, @category.id) %>
                </span>
              </a>
              <a class="nav-link" id="v-pills-tab2" data-toggle="pill" href="#tab2" role="tab" aria-controls="tab2" aria-selected="false">
                Medium Priority
                <span class="badge bg-danger rounded-pill">
                  <%= count_tasks_by_priority_and_status('medium', false, @category.id) %>
                </span>
              </a>
              <a class="nav-link" id="v-pills-tab3" data-toggle="pill" href="#tab3" role="tab" aria-controls="tab3" aria-selected="false">
                Low Priority
                <span class="badge bg-danger rounded-pill">
                  <%= count_tasks_by_priority_and_status('low', false, @category.id) %>
                </span>
              </a>
            </div>
          </div>
          <!-- Conteúdo das tabs -->
          <div class="col-md-10">
            <div class="tab-content" id="v-pills-tabContent">
              <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="v-pills-tab1">
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div id="tasks">
                    <% @tasks.each do |task| %>
                      <% unless task.completion %>
                        <% if task.priority == 'high'%>
                          <%= render 'accordion_item', task: task %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="v-pills-tab2">
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div id="tasks">
                    <% @tasks.each do |task| %>
                      <% unless task.completion %>
                        <% if task.priority == 'medium'%>
                          <%= render 'accordion_item', task: task %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="v-pills-tab3">
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div id="tasks">
                    <% @tasks.each do |task| %>
                      <% unless task.completion %>
                        <% if task.priority == 'low'%>
                          <%= render 'accordion_item', task: task %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <hr>
      <div class="container-fluid">
      <div class="row">
        <!-- Tabs verticais -->
        <div class="col-md-2">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-tab_1" data-toggle="pill" href="#tab_1" role="tab" aria-controls="tab_1" aria-selected="true">
              High Priority
              <span class="badge bg-secondary rounded-pill">
                <%= count_tasks_by_priority_and_status('high', true, @category.id) %>
              </span>
            </a>
            <a class="nav-link" id="v-pills-tab_2" data-toggle="pill" href="#tab_2" role="tab" aria-controls="tab_2" aria-selected="false">
              Medium Priority
              <span class="badge bg-secondary rounded-pill">
                <%= count_tasks_by_priority_and_status('medium', true, @category.id) %>
              </span>
            </a>
            <a class="nav-link" id="v-pills-tab_3" data-toggle="pill" href="#tab_3" role="tab" aria-controls="tab_3" aria-selected="false">
              Low Priority
              <span class="badge bg-secondary rounded-pill">
                <%= count_tasks_by_priority_and_status('low', true, @category.id) %>
              </span>
            </a>
          </div>
        </div>
        <!-- Conteúdo das tabs -->
        <div class="col-md-10">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="tab_1" role="tabpanel" aria-labelledby="v-pills-tab_1">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                <div id="tasks">
                  <% @tasks.each do |task| %>
                    <% if task.completion %>
                      <% if task.priority == 'high'%>
                        <%= render 'accordion_item', task: task %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="tab_2" role="tabpanel" aria-labelledby="v-pills-tab_2">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                <div id="tasks">
                  <% @tasks.each do |task| %>
                    <% if task.completion %>
                      <% if task.priority == 'medium'%>
                        <%= render 'accordion_item', task: task %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="tab_3" role="tabpanel" aria-labelledby="v-pills-tab_3">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                <div id="tasks">
                  <% @tasks.each do |task| %>
                    <% if task.completion %>
                      <% if task.priority == 'low'%>
                        <%= render 'accordion_item', task: task %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>

app/views/tasks/new.html.erb
<center>
    <%= render "form", task: @task %>
</center>